feat: support local filesystem
usememos/memos pull request #1325
Opened 2023-03-09 04:40 UTC by Zeng1998

I merge the commits of front-end and back-end since there are no big changes.

Closes #344 .

2023-03-10 07:36 UTC, HappyZ commented
How do you migrate the data between local and S3 storage?

2023-03-13 01:42 UTC, Zeng1998 commented
> How do you migrate the data between local and S3 storage?

We don't need to do that.

2023-03-13 13:52 UTC, boojack reviewed
And please fix the conflicts

2023-03-13 13:52 UTC, boojack commented on store/resource.go
> +		fields = append(fields, "visibility", "Internal_path")
```suggestion
		fields = append(fields, "visibility", "internal_path")
```

2023-03-13 14:45 UTC, boojack requested changes
There are some irrelevant changes and error messages, please check throughout

2023-03-13 14:45 UTC, boojack commented on api/system_setting.go
> +			return fmt.Errorf("failed to unmarshal system setting openai api host value")
unrelated error message

2023-03-18 06:57 UTC, Zeng1998 commented
Close and re-PR when I have enough time to do it.

2023-03-18 06:57 UTC, closed without merging