Unexpected empty lines when copying-pasting #563
usememos/memos pull request #1524
Opened 2023-04-13 16:24 UTC by ameerturk96

I looked into the issue and I found out when you copy from the memos using keyboard it added an extra line between lines, so what I did was manipulating the innerText when copying using crtl+c and removing the extra line added. looking forward to your feedback.

2023-04-14 12:01 UTC, CorrectRoadH commented
I think to listen Copy Event instead of the Ctrl+C Key-Down Event is a better way to fix the bug.
Such as https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event

2023-04-17 13:24 UTC, ameerturk96 commented
> I think to listen Copy Event instead of the Ctrl+C Key-Down Event is a better way to fix the bug. Such as https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event WDYT?
> 
> I saw your commit, first used the paste event, and then changed it to the ctrl+c event. Why is this? Is there a reason I haven't thought of?

I tried to use the event listener, but because the text is being manipulated before rendering or other reasons that I might don’t know of, the event object only returns the first line "copied", I thought this might be something you know of

2023-04-18 05:17 UTC, CorrectRoadH commented
> > I think to listen Copy Event instead of the Ctrl+C Key-Down Event is a better way to fix the bug. Such as https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event WDYT?
> > I saw your commit, first used the paste event, and then changed it to the ctrl+c event. Why is this? Is there a reason I haven't thought of?
> 
> I tried to use the event listener, but because the text is being manipulated before rendering or other reasons that I might don’t know of, the event object only returns the first line "copied", I thought this might be something you know of

I tried to achieve the same effect based on your idea. 
``` typescript
// MemosList.tsx
...
  useEffect(() => {
    addEventListener("copy", handleCopy);
    return () => {
      removeEventListener("copy", handleCopy);
    };
  }, []);

  const handleCopy = (event: ClipboardEvent) => {
    event.preventDefault();
    const rawStr = document.getSelection()?.toString();
    if (rawStr !== undefined) {
      const splitString = rawStr.split("\n\n");
      const text = splitString.join("\n");
      copy(text);
    }
  };
...
```
The code works fine! This solution is based on yours, but covers more cases (like copy and ctrl+c). WDYT👀

2023-04-18 05:41 UTC, CorrectRoadH requested changes

2023-05-14 03:37 UTC, closed without merging