Add support for image thumbnail
usememos/memos pull request #1641
Opened 2023-05-08 06:32 UTC by athurg

While publishing a large number of HD images, the memoe will take a lot of time to load.

So I just generate a smaller thumbnail while uploading image resources, and only load the thumbnail in the memo. If click on the image, it will load the original HD image lazy.

2023-05-08 06:56 UTC, Zeng1998 commented
I think dynamic compression when loading the image is even more expensive than loading the full image directly.

2023-05-08 07:48 UTC, Zeng1998 reviewed
Do we need to delete the thumbnail in the delete api?

https://github.com/usememos/memos/blob/main/server/resource.go#L273

2023-05-08 07:54 UTC, athurg commented
> Do we need to delete the thumbnail in the delete api?
> 
> https://github.com/usememos/memos/blob/main/server/resource.go#L273

You're right, I have fixed it.

2023-05-09 01:41 UTC, Zeng1998 requested changes

2023-05-09 01:41 UTC, Zeng1998 commented on server/resource.go
> +			err = os.WriteFile(filePath, fileBytes, 0666)
We don't need to modify the original filename.  It should be handled by the path template.

2023-05-14 12:50 UTC, Zeng1998 reviewed
I still recommend that it is best not to modify the original filename, this will break the path template settings.

2023-05-15 07:43 UTC, athurg commented
> I still recommend that it is best not to modify the original filename, this will break the path template settings.

I have changed the thumbnail's naming. Now the original filename was untouched, and the thumbnail file store in a separate cache dir with resource's PublicID as it's filename.

2023-05-15 11:06 UTC, Zeng1998 approved these changes
LGTM

2023-05-15 14:42 UTC, merged

2023-05-16 02:34 UTC, Jonnyan404 commented
> > 我还是建议最好不要修改原来的文件名，这样会破坏路径模板的设置。
> 
> 我已经更改了缩略图的命名。现在原始文件名没有改变，缩略图文件存储在一个单独的缓存目录中，文件名是资源的 PublicID。

为啥昨晚的版本更新,我的不显示缩略图?
还是说必须新上传的才能显示?

2023-05-16 04:13 UTC, athurg commented
> > > 我还是建议最好不要修改原来的文件名，这样会破坏路径模板的设置。
> > 
> > 
> > 我已经更改了缩略图的命名。现在原始文件名没有改变，缩略图文件存储在一个单独的缓存目录中，文件名是资源的 PublicID。
> 
> 为啥昨晚的版本更新,我的不显示缩略图? 还是说必须新上传的才能显示?

It's not a bug. The Resource Dashboard doesn't support the show the thumbnail before, it only shows an icon.

I have add thumbnail support for the Resource Dashboard, please move to #1666 .