Update zh-Hant.json
usememos/memos pull request #1781
Opened 2023-05-31 03:57 UTC by den13501

follow these commits to complete zhTW translation: 96021e518a7fa193576cd509d169c2a9f91f1c3c
8628d1e4b239c2852356f429d3ddbabbc5b35cc4
93d608f0504e5065ecb666601cdd3a58f52742c9
ce64894abe7f691e1db5cf3f9c03d0c93e927fa0
845297ec032e74a11a770a0ed9308d320f07c32f

2023-05-31 04:38 UTC, Zeng1998 requested changes

2023-05-31 04:38 UTC, Zeng1998 commented on web/src/locales/zh-Hant.json
> +      "telegram-user-id-placeholder": "向Telegram機器人傳送任意訊息以獲取",
```suggestion
      "telegram-user-id-placeholder": "向 Telegram 機器人傳送任意訊息以獲取",      
```

2023-05-31 05:26 UTC, Zeng1998 approved these changes
LGTM.

2023-05-31 13:54 UTC, boojack commented
Please fix the json format error

2023-06-01 01:02 UTC, athurg commented
@den13501 I have fixed the JSON format error for you.

You can valid the JSON format before you commit a change and create PR next time: 

:)

2023-06-01 01:03 UTC, boojack approved these changes
LGTM, thanks for your contribution!

2023-06-01 01:03 UTC, merged

2023-06-01 09:21 UTC, den13501 commented
> e JSON format before you commit a change and create PR next time:

Thank you very much, I will be more careful next time!