feat: save message to memo
usememos/memos pull request #1940
Opened 2023-07-13 06:04 UTC by CorrectRoadH

WIP
<img width="748" alt="CleanShot 2023-07-13 at 14 04 48@2x" src="https://github.com/usememos/memos/assets/29306285/b542dab8-3a11-4ecf-99dc-b68e4d545075">

2023-07-15 02:02 UTC, boojack requested changes

2023-07-15 02:02 UTC, boojack commented on web/src/components/MemosChat/MemosChatMessage.tsx
> +  const handelSaveAsMemos = async () => {
typo

```suggestion
  const handleSaveAsMemos = async () => {
```

2023-07-16 02:45 UTC, CorrectRoadH commented
@boojack PTAL

2023-07-16 03:50 UTC, boojack approved these changes
LGTM

2023-07-16 03:51 UTC, merged