Compact Mode Setting (Frontend)
usememos/memos pull request #2936
Opened 2024-02-07 17:15 UTC by MehadND

[Compact Mode Setting (Frontend)](chore: frontend related files for compact view setting.)

2024-02-07 17:27 UTC, MehadND commented
### Demo


https://github.com/usememos/memos/assets/34424878/cb2e7327-e007-4ae1-8bdc-fc1411c1233d

2024-02-09 23:05 UTC, MehadND commented
Please do note that the expand/shrink content is not persistent, in other words, in compact mode:

if a memo is expanded on home page then if user goes to timeline or profile page then same memo will not be expanded but instead will be shrinked.

2024-02-19 11:41 UTC, MehadND commented
@boojack Any chance for you to review this PR? I am certain the backend and DB stuff is already merged, just not the frontend bit. Thank you.

2024-02-19 12:05 UTC, boojack requested changes
Two more thinks:
1. There should be a linear gradients backgound when compact mode enabled;
2. We'd like to go to memo detail page when clicking the `Show more` button.

<img width="750" alt="image" src="https://github.com/usememos/memos/assets/24653555/78810b7f-194c-4c74-b7d3-b10cdecf61e4">

<img width="1353" alt="image" src="https://github.com/usememos/memos/assets/24653555/0bb101e7-cf35-4cba-8140-01453e291e87">

https://tailwindcss.com/docs/background-image#linear-gradients

2024-02-19 12:05 UTC, boojack commented on web/src/components/MemoView.tsx
> +        {showExpandButton && (
Let's go to the detail page of memo when clicking `show more` button.

2024-02-19 12:05 UTC, boojack commented on web/src/components/MemoView.tsx
> +      console.log("Expanding/Shrinking only in compact mode.");
Please remove debug codes.

2024-03-02 08:16 UTC, closed without merging