Centralised the logic for filters to apply to tagging and updated com…
usememos/memos pull request #3515
Opened 2024-06-04 13:04 UTC by mmacdo54

…ponents to pass in those params needed

- Updated the useTagStore fetchTags function to now accept a user and location and it handles the filtering internally
- updated all the places fetchTags was called to pass through the user and location where applicable

Looks to solve the issue where in certain circumstances it finds any public tags

2024-06-04 14:48 UTC, boojack requested changes

2024-06-04 14:48 UTC, boojack commented on web/src/store/v1/tag.ts
> +    fetchTags: async (options: { skipCache?: boolean; user?: User; location?: Location<any> }) => {
It's better to split it into two args.

```suggestion
    fetchTags: async (params?: {user?: User; location?: Location<any> }, options: { skipCache?: boolean }) => {
```

2024-06-04 17:45 UTC, mmacdo54 commented on web/src/store/v1/tag.ts
> +    fetchTags: async (options: { skipCache?: boolean; user?: User; location?: Location<any> }) => {
Yeah good shout.

2024-06-05 00:05 UTC, boojack approved these changes
LGTM

2024-06-05 00:06 UTC, merged