移动端编辑优化
usememos/memos pull request #373
Opened 2022-10-30 05:18 UTC by h2o2o

1. 替换 Emoji Picker 为 Italic 
2. 添加设置光标位置

![移动端编辑优化](https://user-images.githubusercontent.com/70848869/198863748-3b0bf1cd-56df-4d4e-9730-465f4b2a3354.gif)

2022-10-30 05:29 UTC, boojack requested changes

2022-10-30 05:29 UTC, boojack commented on web/src/components/MemoEditor.tsx
> +    setCaretPosition(editorRef.current.getCursorPosition() - 1);
```suggestion
    editorRef.current?.insertText("", "*", "*");
```

2022-10-30 05:29 UTC, boojack commented on web/src/helpers/utils.ts
> +export const setCaretPosition = (pos: number) => {
It will be better to move this function to [`Editor.tsx`](https://github.com/usememos/memos/blob/main/web/src/components/Editor/Editor.tsx#L5).

2022-10-30 05:29 UTC, boojack commented on web/src/components/MemoEditor.tsx
> +    setCaretPosition(editorRef.current.getCursorPosition() - 5);
We should auto select the raw content in `editorRef.current.insertText` instead of changing the caret position manually.

2022-10-30 07:35 UTC, h2o2o commented on web/src/components/MemoEditor.tsx
> +    setCaretPosition(editorRef.current.getCursorPosition() - 5);
> 我们应该自动选择原始内容，而不是手动更改插入符号位置。`editorRef.current.insertText`

我不太明白自动选择是什么意思，您能详细说一下吗？非常感谢。

2022-11-01 14:58 UTC, boojack commented on web/src/components/MemoEditor.tsx
> +    setCaretPosition(editorRef.current.getCursorPosition() - 5);
最理想的情况是在调用 `editorRef.current.insertText` 方法后，自动把当前光标选定到相关的内容里。而不是需要再调用一个函数来设置当前光标位置。

2022-11-13 09:03 UTC, h2o2o commented on web/src/components/MemoEditor.tsx
> +    setCaretPosition(editorRef.current.getCursorPosition() - 5);
最近突然忙了一下，今天有点时间，看到大佬已经弄好了，太厉害了👍

2022-11-13 09:03 UTC, closed without merging